<?php

use Drupal\migrate\Plugin\MigrateSourceInterface;
use Drupal\migrate\Plugin\MigrationInterface;
use Drupal\migrate\Row;

/**
 * Implements hook_migrate_MIGRATION_ID_prepare_row().
 *
 * @throws \Drupal\migrate\MigrateSkipRowException
 * @throws \Exception
 */
function happiness_migrate_migrate_d7_happiness_migrate_hook_prepare_row(Row $row, MigrateSourceInterface $source, MigrationInterface $migration) {
  if ($row->get('field_pin')) {
    $ssn = $row->get('field_pin')[0]['value'];

    /** @var \Drupal\happiness_migrate\Services\PersonalNumberService $personalNumberService */
    $personalNumberService = Drupal::service('happiness_migrate.personal_number_service');

    $personalNumber = $personalNumberService->transform_ssn($ssn);

    if ($personalNumber['status']) {
      $row->setDestinationProperty('field_pin', $personalNumber['value']);
    }
    else {
      $row->setDestinationProperty('status', FALSE);
      $row->setDestinationProperty('field_pin', $ssn);
    }
  }

  return $row;
}
